// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/voitransfer-ui/DarkAI.tsx": () => import("../components/mockups/voitransfer-ui/DarkAI.tsx"),
  "./components/mockups/voitransfer-ui/GlassAI.tsx": () => import("../components/mockups/voitransfer-ui/GlassAI.tsx"),
  "./components/mockups/voitransfer-ui/NeonAI.tsx": () => import("../components/mockups/voitransfer-ui/NeonAI.tsx")
};
